class Flower {
  final String id;
  final String name;
  final String scientificName;
  final String primaryImageUrl;
  final List<String> imageGallery; // ফুলের বিভিন্ন অ্যাঙ্গেলের ছবি
  final String type; // বার্ষিক/দ্বিবার্ষিক/বহুবর্ষজীবী
  final String category; // দেশি/বিদেশি
  final String description;
  final String fragrance; // সুগন্ধের ধরন
  final String bloomTime; // ফোটার সময় (ঋতু)
  final String color; // ফুলের রং
  final String symbolism; // প্রতীকী অর্থ
  final String uses; // ব্যবহার
  final String growthHabit; // বৃদ্ধির ধরণ
  final String leafDescription; // পাতার বর্ণনা
  final String flowerDescription; // ফুলের বিস্তারিত বর্ণনা
  final String habitat; // প্রাকৃতিক বাসস্থান
  final String conservationStatus; // সংরক্ষণ অবস্থা
  final String interestingFacts; // মজার তথ্য
  final String height; // গড় উচ্চতা
  final String lifespan; // জীবনকাল
  final bool isNativeToBangladesh;
  final List<String> regions; // বাংলাদেশে যেসব অঞ্চলে পাওয়া যায়
  final List<String> relatedFlowers; // সম্পর্কিত ফুল

  Flower({
    required this.id,
    required this.name,
    required this.scientificName,
    required this.primaryImageUrl,
    required this.imageGallery,
    required this.type,
    required this.category,
    required this.description,
    required this.fragrance,
    required this.bloomTime,
    required this.color,
    required this.symbolism,
    required this.uses,
    required this.growthHabit,
    required this.leafDescription,
    required this.flowerDescription,
    required this.habitat,
    required this.conservationStatus,
    required this.interestingFacts,
    required this.height,
    required this.lifespan,
    required this.isNativeToBangladesh,
    required this.regions,
    required this.relatedFlowers,
  });
}

// List<Flower> flower = [
//   Flower(
//     id: '1',
//     name: 'গাঁদা',
//     scientificName: 'Tagetes erecta',
//     primaryImageUrl: 'assets/images/flowers/gada.jpg',
//     imageGallery: [
//       'assets/images/flowers/gada1.jpg',
//       'assets/images/flowers/gada2.jpg',
//       'assets/images/flowers/gada3.jpg',
//       'assets/images/flowers/gada4.jpg',
//       'assets/images/flowers/gada5.jpg',
//     ],
//     type: 'বার্ষিক',
//     category: 'দেশি',
//     description:
//         'গাঁদা ফুল বাংলাদেশের সবচেয়ে জনপ্রিয় ও সহজলভ্য ফুলগুলোর মধ্যে একটি।',
//     fragrance: 'তীব্র সুগন্ধযুক্ত',
//     bloomTime: 'শীতকাল',
//     color: 'কমলা, হলুদ',
//     symbolism: 'উজ্জ্বলতা, উষ্ণতা',
//     uses: 'পূজা-অর্চনা, মালা, বাগান সাজানো',
//     growthHabit: 'ছোট গুল্ম, ১-২ ফুট উচ্চতা',
//     leafDescription: 'গাঢ় সবুজ, যৌগিক পাতা, ডিম্বাকার',
//     flowerDescription: 'গোলাকার পুষ্পস্তবক, বহু পাপড়ি',
//     habitat: 'বাগান, পার্ক, বাড়ির আঙিনা',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'গাঁদা ফুল মশা তাড়ানোর জন্য কার্যকর!',
//     height: '৩০-৬০ সেমি',
//     lifespan: '১ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['গন্ধরাজ', 'জিনিয়া', 'ডেইজি'],
//   ),
//   Flower(
//     id: '2',
//     name: 'জবা',
//     scientificName: 'Hibiscus rosa-sinensis',
//     primaryImageUrl: 'assets/images/flowers/joba.jpg',
//     imageGallery: [
//       'assets/images/flowers/joba1.jpg',
//       'assets/images/flowers/joba2.jpg',
//       'assets/images/flowers/joba3.jpg',
//       'assets/images/flowers/joba4.jpg',
//       'assets/images/flowers/joba5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'দেশি',
//     description: 'জবা বাংলাদেশের জাতীয় ফুল এবং একটি জনপ্রিয় বাগান ফুল।',
//     fragrance: 'মৃদু',
//     bloomTime: 'সারা বছর',
//     color: 'লাল, গোলাপী, সাদা, হলুদ',
//     symbolism: 'সৌন্দর্য, নারীত্ব',
//     uses: 'সৌন্দর্যবর্ধন, চুলের যত্ন, ঔষধি',
//     growthHabit: 'ছোট গাছ/গুল্ম, ২-৩ মিটার',
//     leafDescription: 'ডিম্বাকার, দাঁতাযুক্ত কিনারা, গাঢ় সবুজ',
//     flowerDescription: 'বড় আকৃতির, ৫টি পাপড়ি, লম্বা পরাগকেশর',
//     habitat: 'বাগান, বাড়ির আঙিনা',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'জবা ফুলের রস চুল কালো করতে ব্যবহৃত হয়!',
//     height: '২-৩ মিটার',
//     lifespan: '৫+ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['জবা সাদা', 'জবা হলুদ', 'হাইবিস্কাস'],
//   ),
//   Flower(
//     id: '3',
//     name: 'রজনীগন্ধা',
//     scientificName: 'Polianthes tuberosa',
//     primaryImageUrl: 'assets/images/flowers/tuberose.jpg',
//     imageGallery: [
//       'assets/images/flowers/tuberose1.jpg',
//       'assets/images/flowers/tuberose2.jpg',
//       'assets/images/flowers/tuberose3.jpg',
//       'assets/images/flowers/tuberose4.jpg',
//       'assets/images/flowers/tuberose5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'দেশি',
//     description: 'রজনীগন্ধা তার মিষ্টি সুগন্ধের জন্য বিখ্যাত একটি ফুল।',
//     fragrance: 'তীব্র মিষ্টি সুগন্ধ',
//     bloomTime: 'বর্ষাকাল',
//     color: 'সাদা',
//     symbolism: 'শুদ্ধতা, রোমান্স',
//     uses: 'মালা, সুগন্ধি তৈরী, বাগান সাজানো',
//     growthHabit: 'লম্বা ডাঁটা, ২-৩ ফুট',
//     leafDescription: 'লম্বা, সরু, ঘাসের মতো',
//     flowerDescription: 'সাদা, তারার মতো আকৃতি, গুচ্ছবদ্ধ',
//     habitat: 'বাগান, ফুলের বেড',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'একটি রজনীগন্ধা গাছ থেকে ৩০-৪০টি ফুল পাওয়া যায়!',
//     height: '৬০-৯০ সেমি',
//     lifespan: '২-৩ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['গন্ধরাজ', 'গাঁদা', 'চামেলি'],
//   ),
//   Flower(
//     id: '4',
//     name: 'কৃষ্ণচূড়া ফুল',
//     scientificName: 'Delonix regia',
//     primaryImageUrl: 'assets/images/flowers/flame_tree.jpg',
//     imageGallery: [
//       'assets/images/flowers/flame_tree1.jpg',
//       'assets/images/flowers/flame_tree2.jpg',
//       'assets/images/flowers/flame_tree3.jpg',
//       'assets/images/flowers/flame_tree4.jpg',
//       'assets/images/flowers/flame_tree5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'বিদেশি',
//     description: 'কৃষ্ণচূড়া গ্রীষ্মের রাঙা সৌন্দর্যের প্রতীক।',
//     fragrance: 'অতি মৃদু',
//     bloomTime: 'গ্রীষ্মকাল',
//     color: 'লাল, কমলা',
//     symbolism: 'আনন্দ, উৎসব',
//     uses: 'সৌন্দর্যবর্ধন, ছায়াদান',
//     growthHabit: 'বড় গাছ, ছাতার মতো ছড়ানো',
//     leafDescription: 'যৌগিক পাতা, ছোট ছোট পত্রক',
//     flowerDescription: 'বড়, উজ্জ্বল লাল, ৪টি পাপড়ি',
//     habitat: 'রাস্তার ধার, পার্ক',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'একটি পূর্ণবয়স্ক কৃষ্ণচূড়া গাছে হাজার হাজার ফুল ফোটে!',
//     height: '১০-১২ মিটার',
//     lifespan: '৫০+ বছর',
//     isNativeToBangladesh: false,
//     regions: ['শহরাঞ্চল'],
//     relatedFlowers: ['রাধাচূড়া', 'পলাশ', 'শিমুল'],
//   ),
//   Flower(
//     id: '5',
//     name: 'চামেলি',
//     scientificName: 'Jasminum sambac',
//     primaryImageUrl: 'assets/images/flowers/jasmine.jpg',
//     imageGallery: [
//       'assets/images/flowers/jasmine1.jpg',
//       'assets/images/flowers/jasmine2.jpg',
//       'assets/images/flowers/jasmine3.jpg',
//       'assets/images/flowers/jasmine4.jpg',
//       'assets/images/flowers/jasmine5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'দেশি',
//     description: 'চামেলি তার মিষ্টি সুগন্ধের জন্য বিখ্যাত একটি ফুল।',
//     fragrance: 'তীব্র মিষ্টি সুগন্ধ',
//     bloomTime: 'গ্রীষ্মকাল',
//     color: 'সাদা',
//     symbolism: 'শুদ্ধতা, প্রেম',
//     uses: 'মালা, সুগন্ধি, চা',
//     growthHabit: 'লতা বা ছোট গুল্ম',
//     leafDescription: 'গাঢ় সবুজ, ডিম্বাকার, বিপরীতভাবে সজ্জিত',
//     flowerDescription: 'ছোট, সাদা, তারার মতো আকৃতি',
//     habitat: 'বাগান, বাড়ির আঙিনা',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: "চামেলি ফুল বাংলাদেশে 'বেলি ফুল' নামেও পরিচিত!",
//     height: '১-২ মিটার',
//     lifespan: '৫+ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['রজনীগন্ধা', 'গন্ধরাজ', 'মল্লিকা'],
//   ),
//   Flower(
//     id: '6',
//     name: 'সূর্যমুখী',
//     scientificName: 'Helianthus annuus',
//     primaryImageUrl: 'assets/images/flowers/sunflower.jpg',
//     imageGallery: [
//       'assets/images/flowers/sunflower1.jpg',
//       'assets/images/flowers/sunflower2.jpg',
//       'assets/images/flowers/sunflower3.jpg',
//       'assets/images/flowers/sunflower4.jpg',
//       'assets/images/flowers/sunflower5.jpg',
//     ],
//     type: 'বার্ষিক',
//     category: 'বিদেশি',
//     description: 'সূর্যমুখী তার সূর্যের দিকে মুখ করা বৈশিষ্ট্যের জন্য বিখ্যাত।',
//     fragrance: 'মৃদু',
//     bloomTime: 'শীতকাল',
//     color: 'হলুদ',
//     symbolism: 'আনন্দ, উষ্ণতা',
//     uses: 'তৈল উৎপাদন, সৌন্দর্যবর্ধন',
//     growthHabit: 'লম্বা, একক ডাঁটা',
//     leafDescription: 'বড়, হৃদয়াকার, খসখসে',
//     flowerDescription: 'বড়, হলুদ পাপড়ি, গাঢ় বাদামি কেন্দ্র',
//     habitat: 'ক্ষেত, বাগান',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'সূর্যমুখী ফুল সূর্যের দিকে মুখ ঘোরায়!',
//     height: '১-৩ মিটার',
//     lifespan: '১ বছর',
//     isNativeToBangladesh: false,
//     regions: ['উত্তর বাংলাদেশ'],
//     relatedFlowers: ['জিনিয়া', 'ডেইজি', 'গাঁদা'],
//   ),
//   Flower(
//     id: '7',
//     name: 'ডালিয়া',
//     scientificName: 'Dahlia pinnata',
//     primaryImageUrl: 'assets/images/flowers/dahlia.jpg',
//     imageGallery: [
//       'assets/images/flowers/dahlia1.jpg',
//       'assets/images/flowers/dahlia2.jpg',
//       'assets/images/flowers/dahlia3.jpg',
//       'assets/images/flowers/dahlia4.jpg',
//       'assets/images/flowers/dahlia5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'বিদেশি',
//     description: 'ডালিয়া তার বৈচিত্র্যময় রং ও আকৃতির জন্য বিখ্যাত।',
//     fragrance: 'মৃদু থেকে নেই',
//     bloomTime: 'শীতকাল',
//     color: 'লাল, গোলাপী, সাদা, হলুদ, বেগুনি',
//     symbolism: 'আনন্দ, সৃজনশীলতা',
//     uses: 'সৌন্দর্যবর্ধন, ফুলদানি সাজানো',
//     growthHabit: 'গুল্ম, ১-২ মিটার',
//     leafDescription: 'গাঢ় সবুজ, যৌগিক পাতা',
//     flowerDescription: 'বহু পাপড়ি, গোলাকার আকৃতি',
//     habitat: 'বাগান',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'ডালিয়া ফুলের ৪২টি বিভিন্ন প্রজাতি রয়েছে!',
//     height: '৩০-১৫০ সেমি',
//     lifespan: '২-৩ বছর',
//     isNativeToBangladesh: false,
//     regions: ['শহরাঞ্চল'],
//     relatedFlowers: ['ক্রাইস্যান্থেমাম', 'জিনিয়া', 'গাঁদা'],
//   ),
//   Flower(
//     id: '8',
//     name: 'গন্ধরাজ',
//     scientificName: 'Gardenia jasminoides',
//     primaryImageUrl: 'assets/images/flowers/gardenia.jpg',
//     imageGallery: [
//       'assets/images/flowers/gardenia1.jpg',
//       'assets/images/flowers/gardenia2.jpg',
//       'assets/images/flowers/gardenia3.jpg',
//       'assets/images/flowers/gardenia4.jpg',
//       'assets/images/flowers/gardenia5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'দেশি',
//     description: 'গন্ধরাজ তার তীব্র মিষ্টি সুগন্ধের জন্য বিখ্যাত।',
//     fragrance: 'তীব্র মিষ্টি সুগন্ধ',
//     bloomTime: 'গ্রীষ্মকাল',
//     color: 'সাদা',
//     symbolism: 'শুদ্ধতা, প্রেম',
//     uses: 'মালা, সুগন্ধি, বাগান সাজানো',
//     growthHabit: 'ছোট গুল্ম, ১-২ মিটার',
//     leafDescription: 'গাঢ় সবুজ, চকচকে, ডিম্বাকার',
//     flowerDescription: 'সাদা, গোলাকার, বহু পাপড়ি',
//     habitat: 'বাগান',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'গন্ধরাজ ফুল রাতে সবচেয়ে বেশি সুগন্ধ ছড়ায়!',
//     height: '১-২ মিটার',
//     lifespan: '৫+ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['চামেলি', 'রজনীগন্ধা', 'মল্লিকা'],
//   ),
//   Flower(
//     id: '9',
//     name: 'বাগানবিলাস',
//     scientificName: 'Nyctanthes arbor-tristis',
//     primaryImageUrl: 'assets/images/flowers/night_jasmine.jpg',
//     imageGallery: [
//       'assets/images/flowers/night_jasmine1.jpg',
//       'assets/images/flowers/night_jasmine2.jpg',
//       'assets/images/flowers/night_jasmine3.jpg',
//       'assets/images/flowers/night_jasmine4.jpg',
//       'assets/images/flowers/night_jasmine5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'দেশি',
//     description: 'বাগানবিলাস সন্ধ্যায় ফোটে এবং সকালে ঝরে পড়ে।',
//     fragrance: 'মিষ্টি সুগন্ধ',
//     bloomTime: 'বর্ষাকাল',
//     color: 'সাদা পাপড়ি, কমলা কেন্দ্র',
//     symbolism: 'অন্তর্দৃষ্টি',
//     uses: 'পূজা-অর্চনা, ঔষধি',
//     growthHabit: 'ছোট গাছ, ৩-৫ মিটার',
//     leafDescription: 'ডিম্বাকার, খসখসে',
//     flowerDescription: 'সাদা পাপড়ি, কমলা নলাকার কেন্দ্র',
//     habitat: 'বাগান, বাড়ির আঙিনা',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'এই ফুল সন্ধ্যায় ফোটে এবং সকালে ঝরে পড়ে!',
//     height: '৩-৫ মিটার',
//     lifespan: '১০+ বছর',
//     isNativeToBangladesh: true,
//     regions: ['সমগ্র বাংলাদেশ'],
//     relatedFlowers: ['চামেলি', 'গন্ধরাজ', 'রজনীগন্ধা'],
//   ),
//   Flower(
//     id: '10',
//     name: 'করবী',
//     scientificName: 'Nerium oleander',
//     primaryImageUrl: 'assets/images/flowers/oleander.jpg',
//     imageGallery: [
//       'assets/images/flowers/oleander1.jpg',
//       'assets/images/flowers/oleander2.jpg',
//       'assets/images/flowers/oleander3.jpg',
//       'assets/images/flowers/oleander4.jpg',
//       'assets/images/flowers/oleander5.jpg',
//     ],
//     type: 'বহুবর্ষজীবী',
//     category: 'বিদেশি',
//     description: 'করবী একটি বিষাক্ত কিন্তু সুন্দর ফুলের গাছ।',
//     fragrance: 'মিষ্টি',
//     bloomTime: 'সারা বছর',
//     color: 'গোলাপী, সাদা, লাল',
//     symbolism: 'সতর্কতা',
//     uses: 'সৌন্দর্যবর্ধন (সতর্কতার সাথে)',
//     growthHabit: 'গুল্ম, ২-৪ মিটার',
//     leafDescription: 'লম্বা, সরু, চামড়ার মতো',
//     flowerDescription: 'গুচ্ছবদ্ধ, ৫টি পাপড়ি',
//     habitat: 'বাগান, পার্ক',
//     conservationStatus: 'সাধারণ',
//     interestingFacts: 'করবীর সমস্ত অংশ বিষাক্ত!',
//     height: '২-৪ মিটার',
//     lifespan: '১০+ বছর',
//     isNativeToBangladesh: false,
//     regions: ['শহরাঞ্চল'],
//     relatedFlowers: ['ফ্র্যাঞ্জিপানি', 'বুগেনভিলিয়া', 'জবা'],
//   ),
// ];

List<Flower> flower = [
  Flower(
    id: '1',
    name: 'গোলাপ',
    scientificName: 'Rosa spp.',
    primaryImageUrl: 'assets/images/flowers/golap.jpg',
    imageGallery: [
      'assets/images/flowers/golap1.jpg',
      'assets/images/flowers/golap2.jpg',
      'assets/images/flowers/golap3.jpg',
      'assets/images/flowers/golap4.jpg',
      'assets/images/flowers/golap5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description: 'গোলাপ প্রেম ও সৌন্দর্যের প্রতীক হিসেবে বিশ্বজুড়ে পরিচিত।',
    fragrance: 'মিষ্টি সুগন্ধ',
    bloomTime: 'সারা বছর',
    color: 'লাল, গোলাপী, সাদা, হলুদ',
    symbolism: 'প্রেম, সৌন্দর্য',
    uses: 'উপহার, সাজসজ্জা, সুগন্ধি',
    growthHabit: 'গুল্ম, কাঁটাযুক্ত',
    leafDescription: 'সবুজ, ডিম্বাকার, দাঁতাযুক্ত কিনারা',
    flowerDescription: 'বহু পাপড়ি, গোলাকার আকৃতি',
    habitat: 'বাগান, ফুলের টব',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'গোলাপের ১০০টিরও বেশি প্রজাতি রয়েছে!',
    height: '১-২ মিটার',
    lifespan: '৫+ বছর',
    isNativeToBangladesh: false,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['জবা', 'ডালিয়া', 'ক্যামেলিয়া'],
  ),
  Flower(
    id: '2',
    name: 'বেলী',
    scientificName: 'Jasminum sambac',
    primaryImageUrl: 'assets/images/flowers/beli.jpg',
    imageGallery: [
      'assets/images/flowers/beli1.jpg',
      'assets/images/flowers/beli2.jpg',
      'assets/images/flowers/beli3.jpg',
      'assets/images/flowers/beli4.jpg',
      'assets/images/flowers/beli5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'দেশি',
    description: 'বেলী ফুল তার মিষ্টি সুগন্ধের জন্য বিখ্যাত।',
    fragrance: 'তীব্র মিষ্টি সুগন্ধ',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'সাদা',
    symbolism: 'শুদ্ধতা, প্রেম',
    uses: 'মালা, পূজা, সুগন্ধি',
    growthHabit: 'লতা বা ছোট গুল্ম',
    leafDescription: 'গাঢ় সবুজ, ডিম্বাকার',
    flowerDescription: 'ছোট, সাদা, তারার মতো',
    habitat: 'বাগান, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: "বেলী ফুল বাংলাদেশে 'মোতিয়া ফুল' নামেও পরিচিত!",
    height: '১-৩ মিটার',
    lifespan: '৫+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['চামেলি', 'গন্ধরাজ', 'মল্লিকা'],
  ),
  Flower(
    id: '3',
    name: 'শাপলা',
    scientificName: 'Nymphaea nouchali',
    primaryImageUrl: 'assets/images/flowers/shapla.jpg',
    imageGallery: [
      'assets/images/flowers/shapla1.jpg',
      'assets/images/flowers/shapla2.jpg',
      'assets/images/flowers/shapla3.jpg',
      'assets/images/flowers/shapla4.jpg',
      'assets/images/flowers/shapla5.jpg',
    ],
    type: 'জলজ',
    category: 'দেশি',
    description: 'শাপলা বাংলাদেশের জাতীয় ফুল এবং জলাশয়ের সৌন্দর্য।',
    fragrance: 'মৃদু',
    bloomTime: 'বর্ষাকাল',
    color: 'সাদা, নীল, গোলাপী',
    symbolism: 'শুদ্ধতা, শান্তি',
    uses: 'জলাশয় সাজানো, ঔষধি',
    growthHabit: 'জলজ, ভাসমান পাতা',
    leafDescription: 'গোলাকার, ভাসমান, সবুজ',
    flowerDescription: 'বড়, বহু পাপড়ি, ভাসমান',
    habitat: 'পুকুর, দিঘি, জলাশয়',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'শাপলা ফুল সকালে ফোটে এবং সন্ধ্যায় বন্ধ হয়!',
    height: 'জলতল থেকে ১৫-২০ সেমি',
    lifespan: '১ দিন (প্রতিদিন নতুন ফুল)',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['লিলি', 'কমল'],
  ),
  Flower(
    id: '6',
    name: 'কদম',
    scientificName: 'Neolamarckia cadamba',
    primaryImageUrl: 'assets/images/flowers/kodom.jpg',
    imageGallery: [
      'assets/images/flowers/kodom1.jpg',
      'assets/images/flowers/kodom2.jpg',
      'assets/images/flowers/kodom3.jpg',
      'assets/images/flowers/kodom4.jpg',
      'assets/images/flowers/kodom5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description: 'কদম ফুল বাংলাদেশের বর্ষার আগমনী বার্তা বহন করে।',
    fragrance: 'মিষ্টি',
    bloomTime: 'বর্ষাকাল',
    color: 'কমলা-হলুদ',
    symbolism: 'বর্ষা, আনন্দ',
    uses: 'সৌন্দর্যবর্ধন, ঔষধি',
    growthHabit: 'বড় গাছ',
    leafDescription: 'বড়, গাঢ় সবুজ',
    flowerDescription: 'গোলাকার পুষ্পগুচ্ছ',
    habitat: 'বাগান, রাস্তার ধার',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'কদম ফুল বৃষ্টির পর ফোটে!',
    height: '৪৫ মিটার পর্যন্ত',
    lifespan: '৫০+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['জারুল', 'কৃষ্ণচূড়া'],
  ),

  Flower(
    id: '8',
    name: 'বকুল',
    scientificName: 'Mimusops elengi',
    primaryImageUrl: 'assets/images/flowers/bokul.jpg',
    imageGallery: [
      'assets/images/flowers/bokul1.jpg',
      'assets/images/flowers/bokul2.jpg',
      'assets/images/flowers/bokul3.jpg',
      'assets/images/flowers/bokul4.jpg',
      'assets/images/flowers/bokul5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description: 'বকুল ফুল তার মিষ্টি সুগন্ধের জন্য বিখ্যাত।',
    fragrance: 'তীব্র মিষ্টি সুগন্ধ',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'সাদা',
    symbolism: 'প্রেম, আকর্ষণ',
    uses: 'সুগন্ধি, বাগান সাজানো',
    growthHabit: 'মাঝারি আকৃতির গাছ',
    leafDescription: 'ডিম্বাকার, চকচকে',
    flowerDescription: 'ছোট, তারার মতো, সাদা',
    habitat: 'বাগান, পার্ক',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'বকুল ফুল রাতে সবচেয়ে বেশি সুগন্ধ ছড়ায়!',
    height: '১২-১৮ মিটার',
    lifespan: '১০০+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['গন্ধরাজ', 'চামেলি'],
  ),
  Flower(
    id: '9',
    name: 'হাসনাহেনা',
    scientificName: 'Nyctanthes arbor-tristis',
    primaryImageUrl: 'assets/images/flowers/hasnahena.jpg',
    imageGallery: [
      'assets/images/flowers/hasnahena1.jpg',
      'assets/images/flowers/hasnahena2.jpg',
      'assets/images/flowers/hasnahena3.jpg',
      'assets/images/flowers/hasnahena4.jpg',
      'assets/images/flowers/hasnahena5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description: 'হাসনাহেনা সন্ধ্যায় ফোটে এবং সকালে ঝরে পড়ে।',
    fragrance: 'মিষ্টি সুগন্ধ',
    bloomTime: 'বর্ষাকাল',
    color: 'সাদা পাপড়ি, কমলা কেন্দ্র',
    symbolism: 'বিরহ, সৌন্দর্য',
    uses: 'পূজা, ঔষধি',
    growthHabit: 'ছোট গাছ',
    leafDescription: 'ডিম্বাকার, খসখসে',
    flowerDescription: 'সাদা পাপড়ি, কমলা নলাকার কেন্দ্র',
    habitat: 'বাগান, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'এই ফুলের আরেক নাম "পারিজাত"!',
    height: '৩-৫ মিটার',
    lifespan: '১০+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['বাগানবিলাস', 'শিউলি'],
  ),
  Flower(
    id: '10',
    name: 'নাগেশ্বর',
    scientificName: 'Mesua ferrea',
    primaryImageUrl: 'assets/images/flowers/nageshor.jpg',
    imageGallery: [
      'assets/images/flowers/nageshor1.jpg',
      'assets/images/flowers/nageshor2.jpg',
      'assets/images/flowers/nageshor3.jpg',
      'assets/images/flowers/nageshor4.jpg',
      'assets/images/flowers/nageshor5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description: 'নাগেশ্বর সুগন্ধি ফুল ও মূল্যবান কাঠের জন্য বিখ্যাত।',
    fragrance: 'মিষ্টি সুগন্ধ',
    bloomTime: 'বসন্তকাল',
    color: 'সাদা',
    symbolism: 'পবিত্রতা, স্থায়িত্ব',
    uses: 'পূজা-অর্চনা, কাঠ আসবাবপত্রে',
    growthHabit: 'মাঝারি থেকে বড় গাছ',
    leafDescription: 'লম্বা, চকচকে, তামার রঙের নতুন পাতা',
    flowerDescription: 'সাদা, ৪টি পাপড়ি, লম্বা পরাগকেশর',
    habitat: 'বনাঞ্চল, বাগান',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'নাগেশ্বরের কাঠ খুবই শক্ত এবং মূল্যবান!',
    height: '১৫-২০ মিটার',
    lifespan: '১০০+ বছর',
    isNativeToBangladesh: true,
    regions: ['চট্টগ্রাম', 'সিলেট'],
    relatedFlowers: ['নাগকেশর', 'চামেলি'],
  ),
  Flower(
    id: '11',
    name: 'চন্দ্রমল্লিকা',
    scientificName: 'Chrysanthemum morifolium',
    primaryImageUrl: 'assets/images/flowers/chandramallika.jpg',
    imageGallery: [
      'assets/images/flowers/chandramallika1.jpg',
      'assets/images/flowers/chandramallika2.jpg',
      'assets/images/flowers/chandramallika3.jpg',
      'assets/images/flowers/chandramallika4.jpg',
      'assets/images/flowers/chandramallika5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description: 'চন্দ্রমল্লিকা তার বৈচিত্র্যময় রং ও আকৃতির জন্য জনপ্রিয়।',
    fragrance: 'মৃদু',
    bloomTime: 'শীতকাল',
    color: 'সাদা, হলুদ, গোলাপী, বেগুনি',
    symbolism: 'আনন্দ, দীর্ঘায়ু',
    uses: 'সাজসজ্জা, চা',
    growthHabit: 'গুল্ম, গুচ্ছাকার',
    leafDescription: 'গাঢ় সবুজ, খসখসে, ডিম্বাকার',
    flowerDescription: 'বহু পাপড়ি, গোলাকার পুষ্পস্তবক',
    habitat: 'বাগান, টব',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'চন্দ্রমল্লিকা ফুল জাপানের সম্রাটের প্রতীক!',
    height: '৩০-৯০ সেমি',
    lifespan: '২-৩ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['ডেইজি', 'গাঁদা'],
  ),

  Flower(
    id: '12',
    name: 'দোলনচাঁপা',
    scientificName: 'Hedychium coronarium',
    primaryImageUrl: 'assets/images/flowers/dolonchapa.jpg',
    imageGallery: [
      'assets/images/flowers/dolonchapa1.jpg',
      'assets/images/flowers/dolonchapa2.jpg',
      'assets/images/flowers/dolonchapa3.jpg',
      'assets/images/flowers/dolonchapa4.jpg',
      'assets/images/flowers/dolonchapa5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'দেশি',
    description: 'দোলনচাঁপা তার মিষ্টি সুগন্ধ ও সাদা ফুলের জন্য বিখ্যাত।',
    fragrance: 'তীব্র মিষ্টি সুগন্ধ',
    bloomTime: 'বর্ষাকাল',
    color: 'সাদা',
    symbolism: 'শুদ্ধতা, প্রেম',
    uses: 'সৌন্দর্যবর্ধন, সুগন্ধি',
    growthHabit: 'গুল্ম, রাইজোমযুক্ত',
    leafDescription: 'লম্বা, চওড়া, সবুজ',
    flowerDescription: 'সাদা, প্রজাপতি আকৃতির, গুচ্ছবদ্ধ',
    habitat: 'বাগান, জলাশয়ের ধার',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'দোলনচাঁপা কিউবার জাতীয় ফুল!',
    height: '১-২ মিটার',
    lifespan: '৫+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['গন্ধরাজ', 'চামেলি'],
  ),

  Flower(
    id: '13',
    name: 'জুঁই',
    scientificName: 'Jasminum sambac',
    primaryImageUrl: 'assets/images/flowers/jui.jpg',
    imageGallery: [
      'assets/images/flowers/jui1.jpg',
      'assets/images/flowers/jui2.jpg',
      'assets/images/flowers/jui3.jpg',
      'assets/images/flowers/jui4.jpg',
      'assets/images/flowers/jui5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'দেশি',
    description: 'জুঁই ফুল তার তীব্র মিষ্টি সুগন্ধের জন্য বিখ্যাত।',
    fragrance: 'তীব্র মিষ্টি সুগন্ধ',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'সাদা',
    symbolism: 'প্রেম, শুদ্ধতা',
    uses: 'মালা, সুগন্ধি, চা',
    growthHabit: 'লতা বা ছোট গুল্ম',
    leafDescription: 'গাঢ় সবুজ, ডিম্বাকার',
    flowerDescription: 'ছোট, সাদা, তারার মতো',
    habitat: 'বাগান, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'জুঁই ফুল ফিলিপাইনের জাতীয় ফুল!',
    height: '১-৩ মিটার',
    lifespan: '৫+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['বেলী', 'চামেলি', 'মল্লিকা'],
  ),

  Flower(
    id: '14',
    name: 'শিউলি',
    scientificName: 'Nyctanthes arbor-tristis',
    primaryImageUrl: 'assets/images/flowers/sheuli.jpg',
    imageGallery: [
      'assets/images/flowers/sheuli1.jpg',
      'assets/images/flowers/sheuli2.jpg',
      'assets/images/flowers/sheuli3.jpg',
      'assets/images/flowers/sheuli4.jpg',
      'assets/images/flowers/sheuli5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description: 'শিউলি ফুল রাতে ফোটে এবং সকালে ঝরে পড়ে।',
    fragrance: 'মিষ্টি সুগন্ধ',
    bloomTime: 'বর্ষাকাল',
    color: 'সাদা পাপড়ি, কমলা কেন্দ্র',
    symbolism: 'বিরহ, সৌন্দর্য',
    uses: 'পূজা-অর্চনা, ঔষধি',
    growthHabit: 'ছোট গাছ',
    leafDescription: 'ডিম্বাকার, খসখসে',
    flowerDescription: 'সাদা পাপড়ি, কমলা নলাকার কেন্দ্র',
    habitat: 'বাগান, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'শিউলি ফুলকে "রাতের রাণী" বলা হয়!',
    height: '৩-৫ মিটার',
    lifespan: '১০+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['হাসনাহেনা', 'বাগানবিলাস'],
  ),
  Flower(
    id: '15',
    name: 'ক্যামেলিয়া',
    scientificName: 'Camellia japonica',
    primaryImageUrl: 'assets/images/flowers/camellia.jpg',
    imageGallery: [
      'assets/images/flowers/camellia1.jpg',
      'assets/images/flowers/camellia2.jpg',
      'assets/images/flowers/camellia3.jpg',
      'assets/images/flowers/camellia4.jpg',
      'assets/images/flowers/camellia5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description:
        'ক্যামেলিয়া তার নিখুঁত সৌন্দর্য এবং চায়ের সাথে সম্পর্কের জন্য বিখ্যাত।',
    fragrance: 'মৃদু',
    bloomTime: 'শীতকাল',
    color: 'লাল, গোলাপী, সাদা',
    symbolism: 'পরিপূর্ণতা, শ্রদ্ধা',
    uses: 'সাজসজ্জা, চা উৎপাদন',
    growthHabit: 'গুল্ম বা ছোট গাছ',
    leafDescription: 'গাঢ় সবুজ, চকচকে, ডিম্বাকার',
    flowerDescription: 'বহু পাপড়ি, গোলাকার, নিখুঁত আকৃতি',
    habitat: 'বাগান, পার্ক',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'সবুজ চা এবং কালো চা ক্যামেলিয়া সাইনেনসিস গাছ থেকে তৈরি হয়!',
    height: '১.৫-৬ মিটার',
    lifespan: '৫০+ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['গোলাপ', 'ডালিয়া'],
  ),

  Flower(
    id: '16',
    name: 'কাঠগোলাপ',
    scientificName: 'Dalbergia sissoo',
    primaryImageUrl: 'assets/images/flowers/kathgolap.jpg',
    imageGallery: [
      'assets/images/flowers/kathgolap1.jpg',
      'assets/images/flowers/kathgolap2.jpg',
      'assets/images/flowers/kathgolap3.jpg',
      'assets/images/flowers/kathgolap4.jpg',
      'assets/images/flowers/kathgolap5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'দেশি',
    description:
        'কাঠগোলাপ মূল্যবান কাঠ ও সুগন্ধি ফুলের জন্য বিখ্যাত। গাছটি বাংলাদেশের গ্রামাঞ্চলে সাধারণ দেখা যায়।',
    fragrance: 'মৃদু মিষ্টি সুগন্ধ',
    bloomTime: 'বসন্ত থেকে গ্রীষ্মকাল (মার্চ-জুন)',
    color: 'সাদা বা হালকা গোলাপী',
    symbolism: 'স্থায়িত্ব, সৌন্দর্য',
    uses: 'কাঠের আসবাবপত্র, ঔষধি, বাগান সাজানো',
    growthHabit: 'বড় গাছ, ছাতার মতো ছড়ানো',
    leafDescription: 'ছোট, ডিম্বাকার, যৌগিক পাতা, গাঢ় সবুজ',
    flowerDescription: 'ছোট ছোট ফুল গুচ্ছাকারে ফোটে, সাদা বা হালকা গোলাপী',
    habitat: 'গ্রামাঞ্চল, রাস্তার ধার, বাগান',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'কাঠগোলাপের কাঠ বিশ্বের সবচেয়ে দামী কাঠগুলোর মধ্যে একটি!',
    height: '১৫-২৫ মিটার',
    lifespan: '৫০+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ', 'বিশেষত গ্রামাঞ্চল'],
    relatedFlowers: ['শিশু', 'কৃষ্ণচূড়া', 'রাধাচূড়া'],
  ),

  Flower(
    id: '17',
    name: 'ল্যাভেন্ডার',
    scientificName: 'Lavandula angustifolia',
    primaryImageUrl: 'assets/images/flowers/lavender.jpg',
    imageGallery: [
      'assets/images/flowers/lavender1.jpg',
      'assets/images/flowers/lavender2.jpg',
      'assets/images/flowers/lavender3.jpg',
      'assets/images/flowers/lavender4.jpg',
      'assets/images/flowers/lavender5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description:
        'লভেন্ডার তার সুগন্ধি বেগুনি ফুল এবং শান্তিকারক গুণের জন্য বিখ্যাত।',
    fragrance: 'তীব্র সুগন্ধ',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'বেগুনি',
    symbolism: 'শান্তি, বিশুদ্ধতা',
    uses: 'সুগন্ধি, ঔষধি, রান্না',
    growthHabit: 'ছোট গুল্ম',
    leafDescription: 'ধূসর-সবুজ, সরু, সুগন্ধি',
    flowerDescription: 'ছোট, বেগুনি, স্পাইক আকারে গুচ্ছবদ্ধ',
    habitat: 'বাগান, শুষ্ক এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'লভেন্ডার সুগন্ধি ২০০০ বছরেরও বেশি সময় ধরে ব্যবহৃত হয়ে আসছে!',
    height: '৩০-৬০ সেমি',
    lifespan: '৫-১০ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['রোজমেরি', 'কাস্ট uri'],
  ),

  Flower(
    id: '18',
    name: 'লিলি',
    scientificName: 'Lilium spp.',
    primaryImageUrl: 'assets/images/flowers/lily.jpg',
    imageGallery: [
      'assets/images/flowers/lily1.jpg',
      'assets/images/flowers/lily2.jpg',
      'assets/images/flowers/lily3.jpg',
      'assets/images/flowers/lily4.jpg',
      'assets/images/flowers/lily5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description: 'লিলি তার বড় আকৃতি এবং সুন্দর পাপড়ির জন্য বিখ্যাত।',
    fragrance: 'মিষ্টি (কিছু প্রজাতিতে)',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'সাদা, গোলাপী, হলুদ, কমলা',
    symbolism: 'শুদ্ধতা, পুনর্জন্ম',
    uses: 'সাজসজ্জা, উপহার',
    growthHabit: 'বাল্ব থেকে বৃদ্ধি',
    leafDescription: 'লম্বা, সরু, সবুজ',
    flowerDescription: 'বড়, ৬টি পাপড়ি, লম্বা পরাগকেশর',
    habitat: 'বাগান, ফুলের টব',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'কিছু লিলি প্রজাতি বিষাক্ত হতে পারে, বিশেষ করে বিড়ালের জন্য!',
    height: '৩০-১২০ সেমি',
    lifespan: '২-৩ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['শাপলা', 'টিউলিপ'],
  ),

  Flower(
    id: '19',
    name: 'টিউলিপ',
    scientificName: 'Tulipa spp.',
    primaryImageUrl: 'assets/images/flowers/tulip.jpg',
    imageGallery: [
      'assets/images/flowers/tulip1.jpg',
      'assets/images/flowers/tulip2.jpg',
      'assets/images/flowers/tulip3.jpg',
      'assets/images/flowers/tulip4.jpg',
      'assets/images/flowers/tulip5.jpg',
    ],
    type: 'বার্ষিক',
    category: 'বিদেশি',
    description: 'টিউলিপ তার উজ্জ্বল রং এবং অনন্য আকৃতির জন্য বিখ্যাত।',
    fragrance: 'মৃদু বা নেই',
    bloomTime: 'শীতকাল',
    color: 'লাল, গোলাপী, হলুদ, সাদা, বেগুনি',
    symbolism: 'নিখুঁত প্রেম',
    uses: 'সাজসজ্জা, বাগান',
    growthHabit: 'বাল্ব থেকে বৃদ্ধি',
    leafDescription: 'সবুজ, লম্বা, তরবারির মতো',
    flowerDescription: 'কাপের মতো আকৃতি, ৬টি পাপড়ি',
    habitat: 'বাগান, ফুলের টব',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        "১৭শ শতকে নেদারল্যান্ডে 'টিউলিপ ম্যানিয়া' নামে একটি অর্থনৈতিক বুদ্বুদ তৈরি হয়েছিল!",
    height: '১৫-৭৫ সেমি',
    lifespan: '১ বছর (প্রতি বছর নতুন বাল্ব লাগাতে হয়)',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['লিলি', 'ড্যাফোডিল'],
  ),

  Flower(
    id: '20',
    name: 'অ্যাজালিয়া',
    scientificName: 'Rhododendron spp.',
    primaryImageUrl: 'assets/images/flowers/azalea.jpg',
    imageGallery: [
      'assets/images/flowers/azalea1.jpg',
      'assets/images/flowers/azalea2.jpg',
      'assets/images/flowers/azalea3.jpg',
      'assets/images/flowers/azalea4.jpg',
      'assets/images/flowers/azalea5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description: 'অ্যাজালিয়া তার উজ্জ্বল রং ও প্রচুর ফুলের জন্য বিখ্যাত।',
    fragrance: 'কিছু প্রজাতিতে মিষ্টি',
    bloomTime: 'বসন্তকাল',
    color: 'গোলাপী, লাল, সাদা, বেগুনি',
    symbolism: 'নারীসুলভ সৌন্দর্য',
    uses: 'বাগান সাজানো, সাজসজ্জা',
    growthHabit: 'গুল্ম',
    leafDescription: 'ছোট, ডিম্বাকার, গাঢ় সবুজ',
    flowerDescription: 'ট্রাম্পেট আকৃতি, গুচ্ছবদ্ধ',
    habitat: 'বাগান, পার্ক',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'অ্যাজালিয়া নেপালের জাতীয় ফুল!',
    height: '০.৫-২ মিটার',
    lifespan: '১০+ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['রডোডেন্ড্রন', 'ক্যামেলিয়া'],
  ),

  Flower(
    id: '21',
    name: 'ডেইজি',
    scientificName: 'Bellis perennis',
    primaryImageUrl: 'assets/images/flowers/daisy.jpg',
    imageGallery: [
      'assets/images/flowers/daisy1.jpg',
      'assets/images/flowers/daisy2.jpg',
      'assets/images/flowers/daisy3.jpg',
      'assets/images/flowers/daisy4.jpg',
      'assets/images/flowers/daisy5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description: 'ডেইজি তার সরল সৌন্দর্য ও সাদা-হলুদ রংয়ের জন্য বিখ্যাত।',
    fragrance: 'মৃদু',
    bloomTime: 'বসন্তকাল',
    color: 'সাদা পাপড়ি, হলুদ কেন্দ্র',
    symbolism: 'নির্দোষতা, শিশুসুলভতা',
    uses: 'সাজসজ্জা, বাগান',
    growthHabit: 'ছোট গুল্ম',
    leafDescription: 'ছোট, ডিম্বাকার, গাঢ় সবুজ',
    flowerDescription: 'সাদা পাপড়ি, হলুদ কেন্দ্র',
    habitat: 'বাগান, মাঠ',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'ডেইজি ফুল আসলে অনেক ছোট ফুলের সমষ্টি!',
    height: '১০-৩০ সেমি',
    lifespan: '২-৩ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['সূর্যমুখী', 'গাঁদা'],
  ),

  Flower(
    id: '22',
    name: 'গাঁদা',
    scientificName: 'Tagetes erecta',
    primaryImageUrl: 'assets/images/flowers/gada.jpg',
    imageGallery: [
      'assets/images/flowers/gada1.jpg',
      'assets/images/flowers/gada2.jpg',
      'assets/images/flowers/gada3.jpg',
      'assets/images/flowers/gada4.jpg',
      'assets/images/flowers/gada5.jpg',
    ],
    type: 'বার্ষিক',
    category: 'দেশি',
    description:
        'গাঁদা ফুল বাংলাদেশের সবচেয়ে জনপ্রিয় ও সহজলভ্য ফুলগুলোর মধ্যে একটি।',
    fragrance: 'তীব্র সুগন্ধযুক্ত',
    bloomTime: 'শীতকাল',
    color: 'কমলা, হলুদ',
    symbolism: 'উজ্জ্বলতা, উষ্ণতা',
    uses: 'পূজা-অর্চনা, মালা, বাগান সাজানো',
    growthHabit: 'ছোট গুল্ম, ১-২ ফুট উচ্চতা',
    leafDescription: 'গাঢ় সবুজ, যৌগিক পাতা, ডিম্বাকার',
    flowerDescription: 'গোলাকার পুষ্পস্তবক, বহু পাপড়ি',
    habitat: 'বাগান, পার্ক, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'গাঁদা ফুল মশা তাড়ানোর জন্য কার্যকর!',
    height: '৩০-৬০ সেমি',
    lifespan: '১ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['গন্ধরাজ', 'জিনিয়া', 'ডেইজি'],
  ),
  Flower(
    id: '23',
    name: 'জবা',
    scientificName: 'Hibiscus rosa-sinensis',
    primaryImageUrl: 'assets/images/flowers/joba.jpg',
    imageGallery: [
      'assets/images/flowers/joba1.jpg',
      'assets/images/flowers/joba2.jpg',
      'assets/images/flowers/joba3.jpg',
      'assets/images/flowers/joba4.jpg',
      'assets/images/flowers/joba5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'দেশি',
    description: 'জবা বাংলাদেশের জাতীয় ফুল এবং একটি জনপ্রিয় বাগান ফুল।',
    fragrance: 'মৃদু',
    bloomTime: 'সারা বছর',
    color: 'লাল, গোলাপী, সাদা, হলুদ',
    symbolism: 'সৌন্দর্য, নারীত্ব',
    uses: 'সৌন্দর্যবর্ধন, চুলের যত্ন, ঔষধি',
    growthHabit: 'ছোট গাছ/গুল্ম, ২-৩ মিটার',
    leafDescription: 'ডিম্বাকার, দাঁতাযুক্ত কিনারা, গাঢ় সবুজ',
    flowerDescription: 'বড় আকৃতির, ৫টি পাপড়ি, লম্বা পরাগকেশর',
    habitat: 'বাগান, বাড়ির আঙিনা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'জবা ফুলের রস চুল কালো করতে ব্যবহৃত হয়!',
    height: '২-৩ মিটার',
    lifespan: '৫+ বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedFlowers: ['জবা সাদা', 'জবা হলুদ', 'হাইবিস্কাস'],
  ),

  Flower(
    id: '24',
    name: 'কনকচূড়া',
    scientificName: 'Peltophorum pterocarpum',
    primaryImageUrl: 'assets/images/flowers/konokchura.jpg',
    imageGallery: [
      'assets/images/flowers/konokchura1.jpg',
      'assets/images/flowers/konokchura2.jpg',
      'assets/images/flowers/konokchura3.jpg',
      'assets/images/flowers/konokchura4.jpg',
      'assets/images/flowers/konokchura5.jpg',
    ],
    type: 'বহুবর্ষজীবী',
    category: 'বিদেশি',
    description:
        'কনকচূড়া তার উজ্জ্বল হলুদ ফুল ও মিষ্টি সুগন্ধের জন্য বিখ্যাত।',
    fragrance: 'মিষ্টি',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'হলুদ',
    symbolism: 'আনন্দ, উষ্ণতা',
    uses: 'বাগান সাজানো, মালা',
    growthHabit: 'ছোট গাছ',
    leafDescription: 'লম্বা, ডিম্বাকার, গাঢ় সবুজ',
    flowerDescription: '৫টি পাপড়ি, হলুদ, পাপড়ির মাঝে ওভারল্যাপিং',
    habitat: 'বাগান, পার্ক',
    conservationStatus: 'সাধারণ',
    interestingFacts: "কনকচূড়া ফুলের আরেক নাম 'গোল্ডেন অ্যারো'!",
    height: '২-৫ মিটার',
    lifespan: '১০+ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['ফ্রাংগিপানি', 'জবা'],
  ),

  Flower(
    id: '25',
    name: 'জিনিয়া',
    scientificName: 'Zinnia elegans',
    primaryImageUrl: 'assets/images/flowers/zinnia.jpg',
    imageGallery: [
      'assets/images/flowers/zinnia1.jpg',
      'assets/images/flowers/zinnia2.jpg',
      'assets/images/flowers/zinnia3.jpg',
      'assets/images/flowers/zinnia4.jpg',
      'assets/images/flowers/zinnia5.jpg',
    ],
    type: 'বার্ষিক',
    category: 'বিদেশি',
    description: 'জিনিয়া তার উজ্জ্বল রং ও দীর্ঘস্থায়ী ফুলের জন্য বিখ্যাত।',
    fragrance: 'কিছু প্রজাতিতে মৃদু',
    bloomTime: 'গ্রীষ্মকাল',
    color: 'লাল, গোলাপী, হলুদ, কমলা, বেগুনি',
    symbolism: 'স্মৃতি, স্থায়িত্ব',
    uses: 'বাগান সাজানো, ফুলদানি',
    growthHabit: 'গুল্ম',
    leafDescription: 'ডিম্বাকার, খসখসে',
    flowerDescription: 'বহু পাপড়ি, গোলাকার পুষ্পস্তবক',
    habitat: 'বাগান, ফুলের টব',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'জিনিয়া মহাকাশে ফোটানো প্রথম ফুল (আন্তর্জাতিক মহাকাশ স্টেশনে)!',
    height: '৩০-৯০ সেমি',
    lifespan: '১ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল'],
    relatedFlowers: ['ডেইজি', 'গাঁদা'],
  ),
  Flower(
    id: '26',
    name: 'কৃষ্ণচূড়া',
    scientificName: 'Delonix regia',
    primaryImageUrl: 'assets/images/flowers/krishnochura.jpg',
    imageGallery: [
      'assets/images/flowers/krishnochura1.jpg',
      'assets/images/flowers/krishnochura2.jpg',
      'assets/images/flowers/krishnochura3.jpg',
      'assets/images/flowers/krishnochura4.jpg',
      'assets/images/flowers/krishnochura5.jpg',
    ],
    type: 'বৃক্ষ',
    category: 'বিদেশি',
    description:
        'কৃষ্ণচূড়া তার আগুনলাল ফুল ও ছাতার মতো ছড়ানো ডালপালার জন্য বিখ্যাত। গ্রীষ্মকালে পুরো গাছ লাল ফুলে ছেয়ে যায়।',
    fragrance: 'অতি মৃদু',
    bloomTime: 'গ্রীষ্মকাল (এপ্রিল-জুন)',
    color: 'উজ্জ্বল লাল',
    symbolism: 'আনন্দ, গ্রীষ্মের আগমন',
    uses: 'সৌন্দর্যবর্ধন, ছায়াদান, রাস্তার ধারে শোভাবর্ধন',
    growthHabit: 'বড় গাছ, ছাতার মতো ছড়ানো ডালপালা',
    leafDescription: 'ছোট ছোট পত্রক সমৃদ্ধ যৌগিক পাতা, হালকা সবুজ',
    flowerDescription: 'বড় (৮-১০ সেমি), ৪টি পাপড়ি, লম্বা পরাগকেশর',
    habitat: 'রাস্তার ধার, পার্ক, বাগান',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'কৃষ্ণচূড়া মাদাগাস্কারের স্থানীয় গাছ, তবে এখন বাংলাদেশে ব্যাপকভাবে চাষ হয়!',
    height: '১০-১২ মিটার',
    lifespan: '৫০-৭০ বছর',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল', 'রাস্তার ধার', 'উদ্যান'],
    relatedFlowers: ['রাধাচূড়া', 'পলাশ', 'শিমুল'],
  ),
  Flower(
    id: '27',
    name: 'সূর্যমুখী',
    scientificName: 'Helianthus annuus',
    primaryImageUrl: 'assets/images/flowers/sunflower.jpg',
    imageGallery: [
      'assets/images/flowers/sunflower1.jpg',
      'assets/images/flowers/sunflower2.jpg',
      'assets/images/flowers/sunflower3.jpg',
      'assets/images/flowers/sunflower4.jpg',
      'assets/images/flowers/sunflower5.jpg',
    ],
    type: 'বার্ষিক',
    category: 'বিদেশি',
    description:
        'সূর্যমুখী তার উজ্জ্বল হলুদ রঙ এবং সূর্যের দিকে মুখ করা বৈশিষ্ট্যের জন্য বিখ্যাত। এটি একটি তেলবীজ ফসল হিসেবেও গুরুত্বপূর্ণ।',
    fragrance: 'মৃদু',
    bloomTime: 'শীতকাল (নভেম্বর-ফেব্রুয়ারি)',
    color: 'হলুদ (পাপড়ি), বাদামি (কেন্দ্র)',
    symbolism: 'আনন্দ, উষ্ণতা, সূর্যের পূজা',
    uses: 'তেল উৎপাদন, সাজসজ্জা, বীজ作为 খাবার',
    growthHabit: 'লম্বা কান্ড, একক ফুল',
    leafDescription: 'বড়, হৃদয়াকার, খসখসে, গাঢ় সবুজ',
    flowerDescription:
        'বড় আকৃতি (১০-৩০ সেমি), বহু পাপড়ি, গোলাকার বাদামি কেন্দ্র',
    habitat: 'ক্ষেত, বাগান, ফুলের টব',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'সূর্যমুখী ফুল সূর্যের দিকে মুখ ঘোরায় (হেলিওট্রোপিজম)! একটি ফুলে ১,০০০-২,০০০ বীজ থাকতে পারে।',
    height: '১-৩ মিটার',
    lifespan: '১ বছর',
    isNativeToBangladesh: false,
    regions: ['উত্তর বাংলাদেশের চাষাবাদ এলাকা', 'শহরের বাগান'],
    relatedFlowers: ['জিনিয়া', 'গাঁদা', 'ডেইজি'],
  ),
];
