class Fruit {
  final String id;
  final String name;
  final String scientificName;
  final String primaryImageUrl;
  final String type;
  final String category;
  final String description;
  final String benefits;
  final String uses;
  final String growthHabit;
  final String leafDescription;
  final String flowerDescription;
  final String fruitDescription;
  final String barkDescription;
  final String habitat;
  final String conservationStatus;
  final String interestingFacts;
  final String height;
  final String lifespan;
  final String season;
  final bool isNativeToBangladesh;
  final List<String> regions;

  Fruit({
    required this.id,
    required this.name,
    required this.scientificName,
    required this.primaryImageUrl,
    required this.type,
    required this.category,
    required this.description,
    required this.benefits,
    required this.uses,
    required this.growthHabit,
    required this.leafDescription,
    required this.flowerDescription,
    required this.fruitDescription,
    required this.barkDescription,
    required this.habitat,
    required this.conservationStatus,
    required this.interestingFacts,
    required this.height,
    required this.lifespan,
    required this.season,
    required this.isNativeToBangladesh,
    required this.regions,
  });

  factory Fruit.fromJson(Map<String, dynamic> json) {
    return Fruit(
      id: json['id'] ?? '',
      name: json['name'] ?? '',
      scientificName: json['scientificName'] ?? '',
      primaryImageUrl: json['primaryImageUrl'] ?? '',
      type: json['type'] ?? '',
      category: json['category'] ?? '',
      description: json['description'] ?? '',
      benefits: json['benefits'] ?? '',
      uses: json['uses'] ?? '',
      growthHabit: json['growthHabit'] ?? '',
      leafDescription: json['leafDescription'] ?? '',
      flowerDescription: json['flowerDescription'] ?? '',
      fruitDescription: json['fruitDescription'] ?? '',
      barkDescription: json['barkDescription'] ?? '',
      habitat: json['habitat'] ?? '',
      conservationStatus: json['conservationStatus'] ?? 'Common',
      interestingFacts: json['interestingFacts'] ?? '',
      height: json['height'] ?? '',
      lifespan: json['lifespan'] ?? '',
      season: json['season'] ?? '',
      isNativeToBangladesh: json['isNativeToBangladesh'] ?? true,
      regions: List<String>.from(json['regions'] ?? []),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'scientificName': scientificName,
      'primaryImageUrl': primaryImageUrl,
      'type': type,
      'category': category,
      'description': description,
      'benefits': benefits,
      'uses': uses,
      'growthHabit': growthHabit,
      'leafDescription': leafDescription,
      'flowerDescription': flowerDescription,
      'fruitDescription': fruitDescription,
      'barkDescription': barkDescription,
      'habitat': habitat,
      'conservationStatus': conservationStatus,
      'interestingFacts': interestingFacts,
      'height': height,
      'lifespan': lifespan,
      'season': season,
      'isNativeToBangladesh': isNativeToBangladesh,
      'regions': regions,
    };
  }
}

List<Fruit> createFruitsList() {
  final jsonData = [
    {
      "id": "1",
      "name": "আম",
      "scientificName": "Mangifera indica",
      "primaryImageUrl": "assets/images/fruits/mango.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আম একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আম খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আম খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আম ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আম বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "2",
      "name": "কাঁঠাল",
      "scientificName": "Artocarpus heterophyllus",
      "primaryImageUrl": "assets/images/fruits/jackfruit.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "কাঁঠাল একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "কাঁঠাল খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "কাঁঠাল খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "কাঁঠাল ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "কাঁঠাল বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "3",
      "name": "লিচু",
      "scientificName": "Litchi chinensis",
      "primaryImageUrl": "assets/images/fruits/litchi.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "লিচু একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "লিচু খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "লিচু খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "লিচু ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "লিচু বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "4",
      "name": "জাম",
      "scientificName": "Syzygium cumini",
      "primaryImageUrl": "assets/images/fruits/jam.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "জাম একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "জাম খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "জাম খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "জাম ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "জাম বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "5",
      "name": "পেঁপে",
      "scientificName": "Carica papaya",
      "primaryImageUrl": "assets/images/fruits/papaya.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "পেঁপে একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "পেঁপে খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "পেঁপে খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "পেঁপে ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "পেঁপে বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "6",
      "name": "কলা",
      "scientificName": "Musa spp.",
      "primaryImageUrl": "assets/images/fruits/banana.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "কলা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "কলা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "কলা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "কলা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "কলা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "7",
      "name": "নারিকেল",
      "scientificName": "Cocos nucifera",
      "primaryImageUrl": "assets/images/fruits/coconut.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "নারিকেল একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "নারিকেল খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "নারিকেল খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "নারিকেল ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "নারিকেল বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "8",
      "name": "পেয়ারা",
      "scientificName": "Psidium guajava",
      "primaryImageUrl": "assets/images/fruits/guava.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "পেয়ারা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "পেয়ারা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "পেয়ারা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "পেয়ারা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "পেয়ারা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "9",
      "name": "কমলা",
      "scientificName": "Citrus reticulata",
      "primaryImageUrl": "assets/images/fruits/orange.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "কমলা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "কমলা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "কমলা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "কমলা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "কমলা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "10",
      "name": "আতা",
      "scientificName": "Annona squamosa",
      "primaryImageUrl": "assets/images/fruits/sugar_apple.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আতা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আতা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আতা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আতা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আতা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "11",
      "name": "বরই",
      "scientificName": "Ziziphus mauritiana",
      "primaryImageUrl": "assets/images/fruits/jujube.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "বরই একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "বরই খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "বরই খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "বরই ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "বরই বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "12",
      "name": "ডালিম",
      "scientificName": "Punica granatum",
      "primaryImageUrl": "assets/images/fruits/pomegranate.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "ডালিম একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "ডালিম খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "ডালিম খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "ডালিম ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "ডালিম বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "13",
      "name": "আমড়া",
      "scientificName": "Spondias dulcis",
      "primaryImageUrl": "assets/images/fruits/ambarella.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আমড়া একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আমড়া খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আমড়া খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আমড়া ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আমড়া বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "14",
      "name": "জামরুল",
      "scientificName": "Syzygium samarangense",
      "primaryImageUrl": "assets/images/fruits/wax_apple.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "জামরুল একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "জামরুল খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "জামরুল খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "জামরুল ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "জামরুল বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "15",
      "name": "সফেদা",
      "scientificName": "Manilkara zapota",
      "primaryImageUrl": "assets/images/fruits/sapodilla.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "সফেদা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "সফেদা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "সফেদা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "সফেদা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "সফেদা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "16",
      "name": "কামরাঙ্গা",
      "scientificName": "Averrhoa carambola",
      "primaryImageUrl": "assets/images/fruits/star_fruit.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description":
          "কামরাঙ্গা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "কামরাঙ্গা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "কামরাঙ্গা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "কামরাঙ্গা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "কামরাঙ্গা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "17",
      "name": "আনারস",
      "scientificName": "Ananas comosus",
      "primaryImageUrl": "assets/images/fruits/pineapple.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আনারস একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আনারস খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আনারস খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আনারস ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আনারস বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "18",
      "name": "কালোজাম",
      "scientificName": "Syzygium fruticosum",
      "primaryImageUrl": "assets/images/fruits/blackberry.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "কালোজাম একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "কালোজাম খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "কালোজাম খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "কালোজাম ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "কালোজাম বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "19",
      "name": "আঙ্গুর",
      "scientificName": "Vitis vinifera",
      "primaryImageUrl": "assets/images/fruits/grape.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আঙ্গুর একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আঙ্গুর খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আঙ্গুর খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আঙ্গুর ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আঙ্গুর বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "20",
      "name": "আপেল",
      "scientificName": "Malus domestica",
      "primaryImageUrl": "assets/images/fruits/apple.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "আপেল একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আপেল খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আপেল খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আপেল ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আপেল বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "21",
      "name": "নাশপাতি",
      "scientificName": "Pyrus spp.",
      "primaryImageUrl": "assets/images/fruits/pear.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "নাশপাতি একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "নাশপাতি খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "নাশপাতি খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "নাশপাতি ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "নাশপাতি বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "22",
      "name": "আলুবোখারা",
      "scientificName": "Prunus domestica",
      "primaryImageUrl": "assets/images/fruits/plum.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description":
          "আলুবোখারা একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "আলুবোখারা খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "আলুবোখারা খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "আলুবোখারা ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "আলুবোখারা বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "23",
      "name": "পিচ",
      "scientificName": "Prunus persica",
      "primaryImageUrl": "assets/images/fruits/peach.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "পিচ একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "পিচ খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "পিচ খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "পিচ ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "পিচ বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "24",
      "name": "ডুমুর",
      "scientificName": "Ficus carica",
      "primaryImageUrl": "assets/images/fruits/fig.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "ডুমুর একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "ডুমুর খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "ডুমুর খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "ডুমুর ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "ডুমুর বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "25",
      "name": "খেজুর",
      "scientificName": "Phoenix sylvestris",
      "primaryImageUrl": "assets/images/fruits/date.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "খেজুর একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "খেজুর খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "খেজুর খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "খেজুর ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "খেজুর বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "26",
      "name": "তুঁত",
      "scientificName": "Morus alba",
      "primaryImageUrl": "assets/images/fruits/mulberry.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "তুঁত একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "তুঁত খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "তুঁত খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "তুঁত ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "তুঁত বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "27",
      "name": "অ্যাভোকাডো",
      "scientificName": "Persea americana",
      "primaryImageUrl": "assets/images/fruits/avocado.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description":
          "অ্যাভোকাডো একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "অ্যাভোকাডো খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "অ্যাভোকাডো খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "অ্যাভোকাডো ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "অ্যাভোকাডো বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "28",
      "name": "জয়তুন",
      "scientificName": "Olea europaea",
      "primaryImageUrl": "assets/images/fruits/olive.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "জয়তুন একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "জয়তুন খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "জয়তুন খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "জয়তুন ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "জয়তুন বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "29",
      "name": "চেরি",
      "scientificName": "Prunus avium",
      "primaryImageUrl": "assets/images/fruits/cherry.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "চেরি একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "চেরি খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "চেরি খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "চেরি ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "চেরি বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
    {
      "id": "30",
      "name": "তেঁতুল",
      "scientificName": "Tamarindus indica",
      "primaryImageUrl": "assets/images/fruits/tamarind.jpg",
      "type": "Tree",
      "category": "Fruit",
      "description": "তেঁতুল একটি জনপ্রিয় ফল যা বাংলাদেশে ব্যাপকভাবে জন্মে।",
      "benefits":
          "তেঁতুল খেলে শরীরের জন্য উপকারী যেমন ভিটামিন, খনিজ ইত্যাদি পাওয়া যায়।",
      "uses": "তেঁতুল খাওয়া ছাড়াও বিভিন্ন খাদ্য প্রস্তুতিতে ব্যবহৃত হয়।",
      "growthHabit": "মধ্যম থেকে বড় আকৃতির বৃক্ষ।",
      "leafDescription": "সবুজ ও লম্বা পাতা থাকে।",
      "flowerDescription": "ছোট ও মৌসুমভিত্তিক ফুল ফোটে।",
      "fruitDescription": "তেঁতুল ফলটি মিষ্টি বা টক হতে পারে।",
      "barkDescription": "ছাল সাধারণত বাদামী বা ধূসর রঙের।",
      "habitat": "উষ্ণ ও আর্দ্র পরিবেশে ভালো জন্মে।",
      "conservationStatus": "সাধারণ",
      "interestingFacts": "তেঁতুল বাংলাদেশে জনপ্রিয় একটি ফল।",
      "height": "10-15 মিটার",
      "lifespan": "২০-৫০ বছর",
      "season": "গ্রীষ্ম/শীত",
      "isNativeToBangladesh": true,
      "regions": ["Dhaka", "Chittagong", "Rajshahi", "Sylhet"],
    },
  ];

  return jsonData.map((fruitJson) => Fruit.fromJson(fruitJson)).toList();
}
