class Trees {
  final String id;
  final String name;
  final String scientificName;
  final String primaryImageUrl;
  final String type;
  final String category;
  final String description;
  final String benefits;
  final String uses;
  final String growthHabit;
  final String leafDescription;
  final String flowerDescription;
  final String fruitDescription;
  final String barkDescription;
  final String habitat;
  final String conservationStatus;
  final String interestingFacts;
  final String height;
  final String lifespan;
  final String season;
  final bool isNativeToBangladesh;
  final List<String> regions;
  final List<String> relatedTrees;

  Trees({
    required this.id,
    required this.name,
    required this.scientificName,
    required this.primaryImageUrl,
    required this.type,
    required this.category,
    required this.description,
    required this.benefits,
    required this.uses,
    required this.growthHabit,
    required this.leafDescription,
    required this.flowerDescription,
    required this.fruitDescription,
    required this.barkDescription,
    required this.habitat,
    required this.conservationStatus,
    required this.interestingFacts,
    required this.height,
    required this.lifespan,
    required this.season,
    required this.isNativeToBangladesh,
    required this.regions,
    required this.relatedTrees,
  });
}

List<Trees> bangladeshiTrees = [
  Trees(
    id: '1',
    name: 'আম',
    scientificName: 'Mangifera indica',
    primaryImageUrl: 'assets/images/trees/mango.jpg',
    type: 'ফলদ',
    category: 'দেশি',
    description:
        'আম বাংলাদেশের জাতীয় ফল এবং সবচেয়ে জনপ্রিয় গ্রীষ্মকালীন ফল। আম গাছ দীর্ঘজীবী এবং বিশাল আকৃতির হতে পারে।',
    benefits:
        'ভিটামিন এ, সি এবং ই সমৃদ্ধ। হজমশক্তি বৃদ্ধি করে এবং রোগ প্রতিরোধ ক্ষমতা বাড়ায়।',
    uses: 'ফল খাদ্য হিসেবে, কাঠ আসবাবপত্র ও জ্বালানি হিসেবে ব্যবহৃত হয়।',
    growthHabit: 'বৃহৎ আকৃতির চিরসবুজ গাছ',
    leafDescription: 'লম্বা, চকচকে সবুজ পাতা, ১৫-৩৫ সেমি লম্বা',
    flowerDescription: 'ছোট ছোট হলুদাভ ফুল গুচ্ছে ফোটে, সুগন্ধযুক্ত',
    fruitDescription: 'বিভিন্ন আকার ও রঙের রসালো ফল, পাকলে হলুদ বা লাল হয়',
    barkDescription: 'মোটা, গাঢ় বাদামি বাকল, অমসৃণ',
    habitat: 'গ্রীষ্মমন্ডলীয় অঞ্চল',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'আম গাছ ৩০০ বছর পর্যন্ত বাঁচতে পারে! বাংলাদেশে ১০০রও বেশি আমের জাত রয়েছে।',
    height: '৩৫-৪০ মিটার',
    lifespan: '২০০-৩০০ বছর',
    season: 'গ্রীষ্মকাল',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['কাঁঠাল', 'লিচু', 'জাম'],
  ),
  Trees(
    id: '2',
    name: 'কাঁঠাল',
    scientificName: 'Artocarpus heterophyllus',
    primaryImageUrl: 'assets/images/trees/jackfruit.jpg',
    type: 'ফলদ',
    category: 'দেশি',
    description:
        'কাঁঠাল বাংলাদেশের জাতীয় ফল এবং বিশ্বের সবচেয়ে বড় গাছজাত ফল।',
    benefits: 'পুষ্টিগুণে ভরপুর, ক্যালসিয়াম ও পটাসিয়ামের ভালো উৎস।',
    uses: 'ফল, কাঠ আসবাবপত্রে, পাতা গবাদি পশুর খাদ্য',
    growthHabit: 'বড় আকারের চিরসবুজ গাছ',
    leafDescription: 'গাঢ় সবুজ, চকচকে, ডিম্বাকার',
    flowerDescription: 'ছোট, সবুজাভ',
    fruitDescription: 'বিশাল আকৃতির, খসখসে খোলস, ভিতরে কোষ',
    barkDescription: 'গাঢ় বাদামি, অমসৃণ',
    habitat: 'গ্রীষ্মমন্ডলীয় অঞ্চল',
    conservationStatus: 'সাধারণ',
    interestingFacts:
        'একটি পূর্ণবয়স্ক কাঁঠালের ওজন ৩-৫০ কেজি পর্যন্ত হতে পারে!',
    height: '১০-২০ মিটার',
    lifespan: '১০০+ বছর',
    season: 'গ্রীষ্মকাল',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['আম', 'লিচু', 'পেঁপে'],
  ),
  Trees(
    id: '3',
    name: 'নিম',
    scientificName: 'Azadirachta indica',
    primaryImageUrl: 'assets/images/trees/neem.jpg',
    type: 'ঔষধি',
    category: 'দেশি',
    description: 'নিম একটি বহুল ব্যবহৃত ঔষধি গাছ যার প্রতিটি অংশই কাজে লাগে।',
    benefits: 'অ্যান্টিব্যাকটেরিয়াল, অ্যান্টিভাইরাল, রক্ত শোধনকারী',
    uses: 'ঔষধি, কীটনাশক, কাঠ আসবাবপত্রে',
    growthHabit: 'মাঝারি আকৃতির চিরসবুজ গাছ',
    leafDescription: 'পাতা যৌগিক, কিনারা দাঁতাযুক্ত',
    flowerDescription: 'সাদা, ছোট ছোট, সুগন্ধযুক্ত',
    fruitDescription: 'ছোট, ডিম্বাকার, পাকলে হলুদ',
    barkDescription: 'গাঢ় বাদামি, ফাটলযুক্ত',
    habitat: 'শুকনো এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'নিমের তেল ১০০রও বেশি রোগের চিকিৎসায় ব্যবহৃত হয়!',
    height: '১৫-২০ মিটার',
    lifespan: '১৫০-২০০ বছর',
    season: 'বসন্তকাল',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['আম', 'অর্জুন', 'হরিতকী'],
  ),
  Trees(
    id: '4',
    name: 'শিশু',
    scientificName: 'Dalbergia sissoo',
    primaryImageUrl: 'assets/images/trees/shishu.jpg',
    type: 'কাঠ',
    category: 'দেশি',
    description:
        'শিশু বা সিসু গাছ বাংলাদেশের মূল্যবান কাঠের গাছগুলোর মধ্যে একটি।',
    benefits: 'মূল্যবান কাঠ প্রদান করে, মাটি সংরক্ষণে সাহায্য করে',
    uses: 'আসবাবপত্র, ঘর নির্মাণ, জ্বালানি',
    growthHabit: 'দ্রুত বর্ধনশীল, মাঝারি আকৃতির',
    leafDescription: 'যৌগিক পাতা, ৩-৫টি পত্রক',
    flowerDescription: 'সাদা বা গোলাপী, ছোট ছোট',
    fruitDescription: 'ফ্ল্যাট শিম, বীজ ১-৪টি',
    barkDescription: 'গাঢ় বাদামি, গভীর ফাটলযুক্ত',
    habitat: 'নদী তীরবর্তী এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'শিশু কাঠ পানিতে নিমজ্জিত অবস্থায়ও দীর্ঘদিন টিকে থাকে!',
    height: '২৫ মিটার',
    lifespan: '৫০-৭৫ বছর',
    season: 'বসন্তকাল',
    isNativeToBangladesh: true,
    regions: ['সিলেট', 'চট্টগ্রাম', 'রাজশাহী'],
    relatedTrees: ['শাল', 'গামার', 'টিক'],
  ),
  Trees(
    id: '5',
    name: 'কদম',
    scientificName: 'Neolamarckia cadamba',
    primaryImageUrl: 'assets/images/trees/kodom.jpg',
    type: 'সৌন্দর্য্য',
    category: 'দেশি',
    description: 'কদম ফুল বাংলাদেশের গ্রীষ্মকালের একটি পরিচিত দৃশ্য।',
    benefits: 'পরিবেশকে শীতল রাখে, মৌমাছির জন্য ভালো',
    uses: 'সৌন্দর্য্যবর্ধন, কাঠ হালকা কাজে',
    growthHabit: 'দ্রুত বর্ধনশীল, বড় আকৃতির',
    leafDescription: 'বড়, গাঢ় সবুজ, চকচকে',
    flowerDescription: 'কমলা-হলুদ, গোলাকার পুষ্পগুচ্ছ',
    fruitDescription: 'ছোট ছোট ফল, গুচ্ছবদ্ধ',
    barkDescription: 'ধূসর বাদামি, মসৃণ',
    habitat: 'আর্দ্র এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'কদম ফুল বাংলাদেশের বর্ষার আগমনী বার্তা বহন করে!',
    height: '৪৫ মিটার',
    lifespan: '৫০-৭৫ বছর',
    season: 'বর্ষাকাল',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['জারুল', 'কৃষ্ণচূড়া', 'রাধাচূড়া'],
  ),
  Trees(
    id: '6',
    name: 'পলাশ',
    scientificName: 'Butea monosperma',
    primaryImageUrl: 'assets/images/trees/polash.jpg',
    type: 'সৌন্দর্য্য',
    category: 'দেশি',
    description: 'পলাশ বাংলাদেশের বসন্তের অগ্নিময় রঙের প্রতীক।',
    benefits: 'মাটি সংরক্ষণ, মধু উৎপাদন',
    uses: 'সৌন্দর্য্যবর্ধন, ঔষধি, রং তৈরি',
    growthHabit: 'মাঝারি আকৃতির, পাতাঝরা',
    leafDescription: 'ত্রিপত্রক, বড় আকারের',
    flowerDescription: 'উজ্জ্বল কমলা-লাল, গুচ্ছবদ্ধ',
    fruitDescription: 'ফ্ল্যাট শিম, বীজ ১টি',
    barkDescription: 'ধূসর, ফাটলযুক্ত',
    habitat: 'শুকনো এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'পলাশ ফুল থেকে প্রাকৃতিক রং তৈরি করা হয়!',
    height: '১২-১৫ মিটার',
    lifespan: '৫০-৬০ বছর',
    season: 'বসন্তকাল',
    isNativeToBangladesh: true,
    regions: ['মধ্য ও উত্তর বাংলাদেশ'],
    relatedTrees: ['শিমুল', 'কৃষ্ণচূড়া', 'রাধাচূড়া'],
  ),
  Trees(
    id: '7',
    name: 'জাম',
    scientificName: 'Syzygium cumini',
    primaryImageUrl: 'assets/images/trees/jam.jpg',
    type: 'ফলদ',
    category: 'দেশি',
    description:
        'জাম একটি সুস্বাদু ফলদ গাছ যার ফল ডায়াবেটিস রোগীদের জন্য উপকারী।',
    benefits: 'রক্তে শর্করা নিয়ন্ত্রণ করে, অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ',
    uses: 'ফল খাদ্য হিসেবে, কাঠ আসবাবপত্রে',
    growthHabit: 'মাঝারি থেকে বড় আকৃতির',
    leafDescription: 'চকচকে, ডিম্বাকার, গাঢ় সবুজ',
    flowerDescription: 'সাদা, ছোট ছোট, সুগন্ধযুক্ত',
    fruitDescription: 'ছোট, গোলাকার, পাকলে কালো',
    barkDescription: 'ধূসর বাদামি, অমসৃণ',
    habitat: 'গ্রীষ্মমন্ডলীয় অঞ্চল',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'জামের বীজ ডায়াবেটিস নিয়ন্ত্রণে সাহায্য করে!',
    height: '৩০ মিটার',
    lifespan: '১০০+ বছর',
    season: 'গ্রীষ্মকাল',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['আম', 'লিচু', 'জামরুল'],
  ),
  Trees(
    id: '8',
    name: 'কৃষ্ণচূড়া',
    scientificName: 'Delonix regia',
    primaryImageUrl: 'assets/images/trees/krishnochura.jpg',
    type: 'সৌন্দর্য্য',
    category: 'বিদেশি',
    description: 'কৃষ্ণচূড়া বাংলাদেশের গ্রীষ্মের রাঙা সৌন্দর্যের প্রতীক।',
    benefits: 'শীতল ছায়া প্রদান করে, সৌন্দর্য্যবর্ধন',
    uses: 'সৌন্দর্য্যবর্ধন, ছায়াদান',
    growthHabit: 'বড় আকৃতির, ছাতার মতো ছড়ানো',
    leafDescription: 'যৌগিক পাতা, ছোট ছোট পত্রক',
    flowerDescription: 'উজ্জ্বল লাল, বড় আকারের',
    fruitDescription: 'লম্বা, ফ্ল্যাট শিম',
    barkDescription: 'ধূসর বাদামি, মসৃণ',
    habitat: 'গ্রীষ্মমন্ডলীয় অঞ্চল',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'কৃষ্ণচূড়া মাদাগাস্কারের স্থানীয় গাছ!',
    height: '১২ মিটার',
    lifespan: '৫০-৭০ বছর',
    season: 'গ্রীষ্মকাল',
    isNativeToBangladesh: false,
    regions: ['শহরাঞ্চল', 'উদ্যান'],
    relatedTrees: ['রাধাচূড়া', 'পলাশ', 'শিমুল'],
  ),
  Trees(
    id: '9',
    name: 'তাল',
    scientificName: 'Borassus flabellifer',
    primaryImageUrl: 'assets/images/trees/taal.jpg',
    type: 'বহুমুখী',
    category: 'দেশি',
    description: 'তাল গাছ বাংলাদেশের গ্রামীণ জীবনের অবিচ্ছেদ্য অংশ।',
    benefits: 'প্রতিটি অংশই ব্যবহার্য, পরিবেশ রক্ষায় সহায়ক',
    uses: 'ফল, রস, পাতা ছাউনি, কাঠ নির্মাণ কাজে',
    growthHabit: 'লম্বা, সরু কান্ড, শীর্ষে পাতার গুচ্ছ',
    leafDescription: 'বড়, পাখার মতো, পাখার ন্যায় বিভক্ত',
    flowerDescription: 'ছোট, সাদা, গুচ্ছবদ্ধ',
    fruitDescription: 'বড়, গোলাকার, পাকলে কমলা',
    barkDescription: 'কান্ড ধূসর, অমসৃণ, বলয়যুক্ত',
    habitat: 'শুকনো এলাকা',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'একটি তাল গাছ থেকে প্রায় ১০০ লিটার রস সংগ্রহ করা যায়!',
    height: '৩০ মিটার',
    lifespan: '১০০+ বছর',
    season: 'গ্রীষ্মকাল',
    isNativeToBangladesh: true,
    regions: ['উত্তর বাংলাদেশ', 'বরেন্দ্র অঞ্চল'],
    relatedTrees: ['খেজুর', 'নারিকেল', 'সুপারি'],
  ),
  Trees(
    id: '10',
    name: 'বট',
    scientificName: 'Ficus benghalensis',
    primaryImageUrl: 'assets/images/trees/bot.jpg',
    type: 'ছায়াদান',
    category: 'দেশি',
    description: 'বট গাছ বাংলাদেশের জাতীয় গাছ এবং বিশাল ছায়াদানকারী গাছ।',
    benefits: 'বিশাল ছায়া প্রদান করে, বায়ু শোধন করে',
    uses: 'ছায়াদান, ধর্মীয় গুরুত্ব',
    growthHabit: 'বিশাল আকৃতির, বায়বীয় মূলবিশিষ্ট',
    leafDescription: 'বড়, ডিম্বাকার, চকচকে',
    flowerDescription: 'অদৃশ্য, ফল হিসেবে দেখা যায়',
    fruitDescription: 'ছোট, গোলাকার, পাকলে লাল',
    barkDescription: 'হালকা ধূসর, মসৃণ',
    habitat: 'গ্রীষ্মমন্ডলীয় অঞ্চল',
    conservationStatus: 'সাধারণ',
    interestingFacts: 'একটি বট গাছ কয়েক একর জায়গা জুড়ে ছড়িয়ে পড়তে পারে!',
    height: '২০+ মিটার',
    lifespan: '২০০+ বছর',
    season: 'সারা বছর',
    isNativeToBangladesh: true,
    regions: ['সমগ্র বাংলাদেশ'],
    relatedTrees: ['পাকুড়', 'অশ্বথ', 'ডুমুর'],
  ),
];
